### ISSUE TITLE
Improve current acceptance test for maintainability and feasibility

### ISSUE THREAD

**Issue by imjoey** [oVirt/terraform-provider-ovirt#132]
Works to improve acceptance tests:

1. All the variables in testing should be fetched from system environment, instead of hardcode;
2. Trigger the Travis-CI to run acceptance tests for each PR/merge;

**Comment by emesika** [comment]
Sorry for the delay, we are doing a cleanup on all issues in order to be more responsive, is this issue still relevant or we can delete it ?

**Comment by emesika** [comment]
closing this issue , please feel free to reopen if still relevant and provide full details
