### ISSUE TITLE
Drop vendor dir

### ISSUE THREAD

**Issue by rgolangh** [oVirt/terraform-provider-ovirt#148]
go modules is already in place but we still have a vendor dir, which needs to be dropped sooner or later.

**Comment by llomgui** [comment]
Hey,

Why do you want to drop vendor directory?

**Comment by rgolangh** [comment]
Is there a reason to keep build-time deps under the repo? Maybe you have a use-case where you want to embed the repository code into other go project?
Anyhow with go modules, `go build` will download the deps for you.

**Comment by imjoey** [comment]
@rgolangh , I would prefer keep the `vendor` dir, still the vast majority of users start using Go version 1.12+. As the `vendor` is still very helpful for users who are using some dependency management tool such as `glide`, `dep` and etc.

**Comment by rgolangh** [comment]
This issue should probably just handle the move to go modules and vendoring, and not removing the vendor dir.
