### ISSUE TITLE
ovirt_vm resource requires shutdown

### ISSUE THREAD

**Issue by holmesb** [oVirt/terraform-provider-ovirt#166]
Loving this provider.  Only problem I'm having: if I invoke a Terraform script that includes a ovirt_vm resource and that VM is powered-on, execution will hang with messages:
`module.[module_name].ovirt_vm.[vm_name]: Still modifying... [id=[id], 1m20s elapsed]`

Until eventually it times-out after 10 minutes:
`Error: Error starting vm: timeout while waiting for state to become 'down' (last state: 'up', timeout: 10m0s)`

The only way to apply my changes is to manually shutdown the VM during execution, either through the ovirt-engine webui or cli.  The moment the machine is off, execution proceeds to completion fine.  I'm expecting scripts that haven't changed to execute fine on started VMs.

Strangely, if I invoke a Terraform script that includes a ovirt_vm resource and that VM is already powered-off, Terraform will **start** the VM, and execution will hang same as above until I power-off the VM again.

Happens with one or many VMs defined.  I'm on Terraform 12.4 and latest ovirt provider compiled from master.  VMs are ubuntu with ovirt guest-agent v1.0.13.dfsg-2.

Any ideas?  Is this because the provider needs to shutdown VMs during execution for some reason and is failing to do so?

**Comment by imjoey** [comment]
Hi @holmesb , many thanks for reporting this. Obviously I screwed up the updating progress of VM resource. Currently, VM updating will be only triggered when the `initialization` attribute changes. We should never power off the VM since the `initialization` attribute supports live update.

As for starting a VM automatically, could you please provider the terraform configurations? That  would be great with the output of `terraform plan`. Thanks very much.

**Comment by holmesb** [comment]
> "VM updating will be only triggered when the initialization attribute changes. We should never power off the VM since the initialization attribute supports live update." 
To be clear, the provider doesn't power off the VM, it just doesn't execute until the VM is manually powered-off.  So does that mean this is a confirmed bug?  I'll reduce my code to a simpler example and send it later this week.

**Comment by imjoey** [comment]
Yes,  it's a bug indeed. Current implementation will try to power off VM when doing updates, as shown in log  `Error: Error starting vm: timeout while waiting for state to become 'down' (last state: 'up', timeout: 10m0s`.

**Comment by imjoey** [comment]
Hi @holmesb , this issue has been fixed within #167 and included in the latest `v0.4.1` release. You could update and rerun your codes.  If anything unexpected still occurs, please let me know. Thanks.

**Comment by holmesb** [comment]
Fixed.  VMs no longer need to be shutdown before execution will complete.  Seems the "live update" change you made did the trick :-)

**Comment by imjoey** [comment]
Very glad it worked. Thanks again for your reporting.
