### ISSUE TITLE
Support for Target Storage Domain for VM Lease

### ISSUE THREAD

**Issue by cyberworm54** [oVirt/terraform-provider-ovirt#171]
Right now if you use the ovirt_vm resource and create a vm from a template which is setup for a Target Storage Domain for VM Lease (which means if HA is enabled and the lease is created within the vm storage, that vm will be killed and restarted on another host in case of host failure) is not set. It is set to ```no vm lease``` and ```auto resume``` which only works if the failed host comes back online, which means that the vm will not be restarted on another host. When you create a VM fron  Ovirt console and enable the HA flag, Ovirt by default will create a lease for that domain, which is the desired configuration.

**Comment by imjoey** [comment]
Hi @cyberworm54 , thanks for reporting and also I apologize for the late reply. The VM lease functionality is not supported yet currently. I would try to fix this, probably by adding some missing attributes or resources. Thanks.

**Comment by emesika** [comment]
Sorry for the delay, we are doing a cleanup on all issues in order to be more responsive, is this issue still relevant or we can delete it ?

**Comment by cyberworm54** [comment]
You can go ahead and delete it. Thanks!
