### ISSUE TITLE
Get IP address of the new VM

### ISSUE THREAD

**Issue by beremtl** [oVirt/terraform-provider-ovirt#172]
Hi, is anyone know how I can get an IP address of the VM, that  I just create?
I try throught the data source "ovirt_vms", but he hasn't have it

**Comment by imjoey** [comment]
Hi @beremtl , thanks for reporting. Currently the IP address is not exportable and sorry for the inconvenience. I would make it fixed. Thank you very much.

**Comment by beremtl** [comment]
@imjoey thanks. It will be great.

**Comment by imjoey** [comment]
Hi @beremtl , sorry for late response. The new release `v0.4.2` is out, which has #174 and #173 merged in that supports the IP addresses of a VM exportable. Now we could use the attribute `vms.0.reported_devices.0.ips.0.address` of data source `ovirt_vms`, or `nics.0.reported_devices.0.ips.0.address` of new data source `ovirt_nics`,   to retrieve the IP address of a given VM.

About the definition of reported devices, please see  [vm reported devices](http://ovirt.github.io/ovirt-engine-api-model/4.4/#services/vm_reported_devices) for details. Thanks.

**Comment by beremtl** [comment]
@imjoey Thank you so much!! It's works perfect! Now I can automatically run ansible script on vm.

**Comment by imjoey** [comment]
Hi @beremtl  So glad to see it works.  😄   Thank you very much for your feedback.
