### ISSUE TITLE
Unable to set network on RHEV VM

### ISSUE THREAD

**Issue by gangadhar01a** [oVirt/terraform-provider-ovirt#179]
Hi,

I have been using the ovirt provider to provision VM on RHEV. I would like to use cloud init to set up network, following are the terraform configuration files 

RHEV_VM.tf
_resource "ovirt_vm" "prod-2" {
  name        = "${local.hostname1}"
  cluster_id  = "${data.ovirt_clusters.default.clusters.0.id}"
  template_id = "1234567809"
  memory      = "16000"
  cores       = "6" 
  initialization {
    custom_script = "${data.template_file.cloud_init_vm1.rendered}"
    dns_servers   = "XX.XXX.XXX.XXXX"
    dns_search    = "iamhere.net"
    nic_configuration {
      label      = "eth0"
      boot_proto = "static"
      address    =  "XX.XXX.XX.XXX"
      netmask    = "XX.XXXX.XXXX"
      gateway    = "XX.XXX.XX.X"
      on_boot    = true
    }   
  }
}
resource "ovirt_vnic" "prod-2" {
  vm_id           = "${ovirt_vm.prod-symfonyworker-2.id}"
  name            = "nic1"
  vnic_profile_id = "${data.ovirt_vnic_profiles.vnic_profile.vnic_profiles.0.id}"
}
data "template_file" "cloud_init_vm1" {
  template = "${file("cloud-init.yml")}"
}_

cloud_init.yaml
_hostname: "prod-2.imhere.net"
fqdn: "prod-2.imhere.net"

runcmd:

 - touch /etc/cloud/cloud-init.disabled_

After the execution of terraform code, I can see the network details (cloud init) in RHEV GUI but the network has been not set up on the VM.

**Comment by gangadhar01a** [comment]
I love to say "cloud init" works, I haven't installed cloud init utils in my template.

**Comment by imjoey** [comment]
@gangadhar01a  Thank you for this and glad to see issue resolved. Feel free to reopen if necessary.
