### ISSUE TITLE
Examples don't work in the latest Terraform version

### ISSUE THREAD

**Issue by Oddly** [oVirt/terraform-provider-ovirt#186]
Running the examples with latest terraform(0.12.16) creates some errors. For example, from main.tf:

Error: Warning: Interpolation-only expressions are deprecated
Solution: Remove "${" and "}" from those expressions, they are deprecated.

I can adjust it, I just needed to know whether we will do backwards compat to earlier Terraform versions, or will we adjust this to work with 0.12.16?

**Comment by imjoey** [comment]
@Oddly Great thoughts and thanks for your contribution. With regards to the backward compatibility, I would prefer to announce a higher version, as well as inform users of the incompatibility issues in README file. This will let users decide which version to be adopted as needed. 

Any thoughts on this? @rgolangh

**Comment by Oddly** [comment]
Thanks for the feedback! I'll just keep an eye on this then, I'll be happy to test things.

**Comment by imjoey** [comment]
> Thanks for the feedback! I'll just keep an eye on this then, I'll be happy to test things.

@Oddly Much appreciated. I'll make this issue resolved ASAP. Any feedback is welcome. Thanks.

**Comment by ValentinoUberti** [comment]
I've got this error running the example from vm directory:

Error: Tag not matched: expect <fault> but got <html>
  on main.tf line 54, in resource "ovirt_vnic_profile" "vm_vnic_profile":
  54: resource "ovirt_vnic_profile" "vm_vnic_profile" {

**Comment by rgolangh** [comment]
@ValentinoUberti can you try with the latest provider compiled?

**Comment by emesika** [comment]
Sorry for the delay, we are doing a cleanup on all issues in order to be more responsive, is this issue still relevant or we can delete it ?

**Comment by janosdebugs** [comment]
The new Terraform provider is now available on the registry and all examples should work now.
