### ISSUE TITLE
ovirt_image_transfer: The string '' isnt a valid value for the DiskFormat 

### ISSUE THREAD

**Issue by CS-AE** [oVirt/terraform-provider-ovirt#187]
Hello,
Hoping this is a mistake on my part somewhere, I am trying to add an image via ovirt_image_transfer but I am getting the response stating that the DiskFormat is defaulting to an empty string:

`Error: Fault reason is "Invalid value". Fault detail is "The string '' isn't a valid value for the 'DiskFormat' enumerated type. Valid values are: 'cow', 'raw'.". HTTP response code is "400". HTTP response message is "400 Bad Request".`

HCL for the image transfer:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

create

Terraform will perform the following actions:

ovirt_image_transfer.core_image will be created
resource "ovirt_image_transfer" "c_image" {
alias             = "c_image"
disk_id           = (known after apply)
id                = (known after apply)
source_url        = "http://"
sparse            = true
storage_domain_id = "dfe99181-3902-5d14-bdcd-5ch2237fbe8e"
}
```
I am not used to dealing with go as a language or the structure otherwise i'd have had a poke around myself on how its defined. 

Is there a way of specifying the disk format ?

**Comment by duritong** [comment]
Getting the same while trying to import FCOS:

```
  + resource "ovirt_image_transfer" "fcos_transfer" {
      + alias             = "fcos-31-bx2-Local"
      + disk_id           = (known after apply)
      + id                = (known after apply)
      + source_url        = "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200113.3.1/x86_64/fedora-coreos-31.20200113.3.1-openstack.x86_64.qcow2.xz"
      + sparse            = true
      + storage_domain_id = "d3d21d97-3ec9-4b37-b0e0-f94f0851d808"
    }
```

**Comment by duritong** [comment]
So I was able to go one step further when I downloaded the image decrompessed it (using `xz -d`) and gave the `source_url`a local file path. Based on the source code I read ovirt terraform should then be able to detect the right format.

**Comment by imjoey** [comment]
Hi @CS-AE and @duritong , sorry for being late and firstly thanks for your contributions. Could you please provide the version of ovirt-engine?  I'll take a deep look soon. Thanks again.

**Comment by duritong** [comment]
Thanks for looking into it I am running: 4.3.6.7
