### ISSUE TITLE
vm boot devices

### ISSUE THREAD

**Issue by mathianasj** [oVirt/terraform-provider-ovirt#189]
I would like to see the ability to set the boot devices.  I am working on a PR to do this.

**Comment by imjoey** [comment]
Hi @mathianasj , thanks. Your PR is much appreciated. Please let me know if you have any troubles.

**Comment by imjoey** [comment]
Hi @mathianasj , just a reminder of the dependency of this repo for go-ovirt SDK has been upgraded to 4.4.1, which fix the incorrect tag of `boot_device`. Thanks for your great efforts. 😄
