### ISSUE TITLE
Failed to find StartElement

### ISSUE THREAD

**Issue by jangel97** [oVirt/terraform-provider-ovirt#193]
Hello there,

I am currently introducing myself to Terraform and I am quite eager in using this oVirt provider. The thing is that after trying several times I always get the same error in my project 
![image](https://user-images.githubusercontent.com/38217290/73756183-70545500-4767-11ea-9727-5d6c18e5aec5.png)

I have also tried with the examples provided in this repository and I am also experiencing the same error. :(

I don't know if it really is a problem of mine or a bug.

Hope you guys shed some light on this issue, thanks in advance!

My terraform version is: v0.11.14
My oVirt RHV platform is  4.1.7.6-0.1.el7
I am using a template to build the VM.

**Comment by imjoey** [comment]
Hi @jangel97 , I guess the tf file is with invliad format. Could you please paste your tf configurations?

**Comment by jangel97** [comment]
main.tf file: `
// Create cloud-init scutom-script from template templates/cloud-init-script.yml.tpl
data "template_file" "cloud_init_script" {
  template = "${file("${path.module}/templates/cloud-init-script.yml.tpl")}"

  vars {
    ssh_pub_key = "${var.ssh_pub_key}"
    repo_server = "${var.repo_server}"
    hostname    = "${var.host_name}"   
  }
}

// Render cloud init template
data "template_cloudinit_config" "ovirt_cloud_init" {
  gzip          = false
  base64_encode = false

  part {
    content_type = "text/cloud-config"
    content      = "${data.template_file.cloud_init_script.rendered}"
  }
}

// Create vm from cloud-init template
resource "ovirt_vm" "vm" {
  name = "${var.name}"

  cluster_id = "${var.cluster_id}"
  template_id = "${var.template_id}"

  memory = "${var.memory}"
  cores = "${var.cores}"
  sockets = "${var.sockets}"
  threads = "${var.threads}"
  high_availability = "${var.high_availability}"

initialization {
   authorized_ssh_key = "${var.ssh_pub_key}"

    host_name = "${var.host_name}"
    timezone = "${var.timezone}"
    user_name = "${var.user_name}"
    #custom_script = "${data.template_cloudinit_config.ovirt_cloud_init.rendered}"
    custom_script = "${data.template_file.cloud_init_script.rendered}"
    dns_search = "${var.dns_search}"
    dns_servers = "${var.dns_servers}"
    
    nic_configuration {
      label = "${var.label}"
      boot_proto = "${var.boot_proto}"
      address = "${var.address}"
      gateway = "${var.gateway}"
      netmask = "${var.netmask}"
      on_boot = "${var.on_boot}"
    }
}
}
`
provider.tf

`
// Set provider config
provider "ovirt" {
  username = "${var.ovirt_username}"
  url      = "${var.ovirt_url}"
  password = "${var.ovirt_pass}"
}

`
This is my vars file:
variable "ovirt_url" {
  description = "The oVirt engine URL"
  default = "https://he1.my.lab
[myfiles-zip.zip](https://github.com/oVirt/terraform-provider-ovirt/files/4154292/myfiles-zip.zip)
/ovirt-engine/api"
}

variable "ovirt_username" {
  description = "The name of user to access oVirt engine API"
  default = "admin@internal"
}

variable "ovirt_pass" {
  description = "password."
}


### variables for creating vm ###
variable "cluster_id" {
  description = "The ID of cluster"
  default = "Default"
}

variable "storagedomain_id" {
  description = "The ID of storage domain"
   default = "data_1"
}

variable "template_id" {
  description = "The ID of VM template"
  default = "6298cc5d-a721-4015-b01a-71349b323208"      # rhel7.4-cloud-init in DC_TEST
}

variable "network_id" {
  description = "The ID of network"
  default = "00000000-0000-0000-0000-000000000009"
}

variable "cores" {
  default = "1"
}

variable "high_availability" {
  default = "true"
}

variable "memory" {
  default = "4096"
}

variable "name" {
  default = "test-tf-provider"
}
variable "sockets" {
  default = "1"
}

variable "threads" {
  default = "1"
}

# variables used for cloud-init
variable "host_name" {
  default = "testcloud1"
}

variable "timezone" {
  default = "Europe/Budapest"
}

variable "user_name" {
  default = "root"
}

variable "ssh_pub_key" {
  default = "ssh-rsa ...."      # set your SSHv2 pub key here
}

variable "repo_server" {
  default = "192.168.4.4"
}

variable "dns_search" {
  default = "domain"
}

variable "dns_servers" {
  default = "8.8.8.8"
}

variable "label" {
  default = "eth0"
}

variable "boot_proto" {
  default = "static"
}

variable "address" {
  default = "172.16.1.123"
}
variable "gateway" {
  default = "172.16.1.1"
}

variable "netmask" {
  default = "255.255.255.0"
}

variable "on_boot" {
  default = "true"
}

I have attached in a zip file my project so you can check more clearly if you need.

The problem is that I do not really know why I encounter this behaviour and actually never happened with other providers such us libvirt or vsphere.

**Comment by jangel97** [comment]
Hey, 

I updated my terraform to the latest release version and I am still facing the same issue: "Failed to find StartElement", what do you think guys?

**Comment by ValentinoUberti** [comment]
Same here. Does somebody succesfully run this plugin?

**Comment by rgolangh** [comment]
First download the latest plugin release. We bumped the API version of it.

Please export TF_LOG=DEBUG and run `terraform plan` . if the failure is not there then run `terraform apply`

Can you test is with a simple hcl file like:
```
provider "ovirt" {
  username = "admin@internal"
  url      = "https://yourfqdn/ovirt-engine/api"
  password = "secret
}
data "ovirt_disks" "filtered_disks" {
  search = {
    criteria       = "*"
  }
}

output "disks" {
  value = data.ovirt_disks.filtered_disks
}
```

```

**Comment by emesika** [comment]
Sorry for the delay, we are doing a cleanup on all issues in order to be more responsive, is this issue still relevant or we can delete it ?

**Comment by jangel97** [comment]
I am not working with rhev provider anymore. Feel free to delete the issue.
Thx!
