### ISSUE TITLE
Create a branch/release for pre plugin-sdk release

### ISSUE THREAD

**Issue by rgolangh** [oVirt/terraform-provider-ovirt#196]
This issue is release oriented. 

Motivation
OKD installer [1] is vendoring the provider, along with few others and all 
of them, till certain point in time[2]  still don't use the terraform plugin-sdk. 
Now I'm in a point where I need to fix something in the provider, and to revendor
it, but I'm blocked because our provider already migrated to the plugin-sdk [3]
Hence I need a way to consume and maintain a version which is still pre plugin sdk. 

The way to do it is most probably to branch from [3] and cherry pick fixes on top.

@imjoey Since I didn't create any release on this repo yet I want hear your thoughts about how to address that.

[1] https://github.com/openshift/installer
[2] https://github.com/openshift/installer/pull/2745
[3] https://github.com/oVirt/terraform-provider-ovirt/pull/188

**Comment by imjoey** [comment]
@rgolangh , IMO, a new branch is good choice for this. While I still have two more questions:
- Need the new branch to release a series of versions? Is that possible just use commit id for importing?
- How long will the new (temporary) branch exist for ?

**Comment by rgolangh** [comment]
> @rgolangh , IMO, a new branch is good choice for this. While I still have two more questions:
> 
>     * Need the new branch to release a series of versions? Is that possible just use commit id for importing?
>

Do you mean for cherry picking?
 
>     * How long will the new (temporary) branch exist for ?
> 
OKD 4.4 installer uses that and it only changes in 4.5. For me it should be there as long as OKD .4.4 will use it.

> 
> Thanks.

**Comment by rgolangh** [comment]
- created the branch https://github.com/oVirt/terraform-provider-ovirt/tree/terraform-v012.2 
- excluded a925cff 05d3363 576b8da
- updated the vendor of go-ovirt for de3215c
- done

Rebase is clean and the diff shows only changes to the import statements:
`git diff origin/master origin/terraform-v0.12.2 ovirt/`

**Comment by rgolangh** [comment]
Also left a comment on the README to note about the terraform version
https://github.com/oVirt/terraform-provider-ovirt/tree/terraform-v012.2

**Comment by rgolangh** [comment]
@imjoey Before closing this, do you have any way to automate cherry picks? github actions? travis?

**Comment by rgolangh** [comment]
closing for now. CI is a different topic we need to handle.
