### ISSUE TITLE
Failed to start VM because "Request syntactically incorrect"

### ISSUE THREAD

**Issue by johnsimcall** [oVirt/terraform-provider-ovirt#212]
I'm unable to start VMs with:
- provider:  built from master (74a154c)
- Terraform v0.12.24
- ovirt-engine-4.3.8.2-0.4.el7.noarch (RHVM 4.3.8)

The VM is created successfully in a stopped/down state.  Terraform fails when trying to start the VM with this error

Error: Fault reason is "Request syntactically incorrect.". Fault detail is "For correct usage, see: https://my.rhv.lab/ovirt-engine/apidoc#services/vm/methods/start". HTTP response code is "400". HTTP response message is "400 Bad Request".

**Comment by johnsimcall** [comment]
My main.tf file and the TF_LOG=trace logs are available at https://pastebin.com/LpFQTBVD

**Comment by johnsimcall** [comment]
Looks like a simple upgrade may have fixed my problem.  I did a "yum upgrade && engine-setup" on my RHVM server, and it works now.

- ovirt-engine-4.3.9.4-11.el7.noarch

**Comment by Gal-Zaidman** [comment]
thanks, new version supposed to support 4.4.5 and above so closing this one :)
