### ISSUE TITLE
tag a new version and release it to the terraform registry

### ISSUE THREAD

**Issue by attachmentgenie** [oVirt/terraform-provider-ovirt#230]
hashicorp recently created the ability to release to and install community developed providers from their registry [1]. this dramatically reduces the complexity of using the providers in terraform 0.13. 

publishing a release to the registry requires finishing the terraform registry setup (that person needs admin permissions on this repository), Setting a gpg key (and sharing the public part with hashicorp) as a github secret, and running the workflow from the template project. 

[1] https://www.hashicorp.com/blog/announcing-providers-in-the-new-terraform-registry
[2] https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by openstandards** [comment]
This would certainly be an improvement as the installation as it would make installation easier and place documentation on terraform registry.

**Comment by attachmentgenie** [comment]
@emesika is there any way i can help to get this going?

**Comment by emesika** [comment]
@attachmentgenie  , Yes , can you issue a PR for that ??

**Comment by attachmentgenie** [comment]
@emesika happy to help but i am not entirely sure what that does entail for this particular project.

**Comment by attachmentgenie** [comment]
by the looks of it, it just requires updating the the change log, i am sure i can convince goreleaser to create that for us

**Comment by attachmentgenie** [comment]
@emesika i generated a new changelog entry in #241.

**Comment by janoszen** [comment]
@attachmentgenie thank you for your help in this matter. We had a relatively urgent release to do (v4.4.5-r.0 coming now), but this is next up on our radar.

**Comment by attachmentgenie** [comment]
@janoszen as i said, anyway i can help? i have setup the registry for some other providers as well

**Comment by janoszen** [comment]
@attachmentgenie thank you very much for your offer to help. Right now our main concern is getting a working CI / testing system working so PRs can be checked automatically. Once that's done we can be sure that any changes made to the PR don't break compatibility and we can safely start releasing to the TF registry.

**Comment by cervajs** [comment]
this will help a lot. actually battling after update to terraform 0.15 with directory/filename schema for ovirt plugin

**Comment by cervajs** [comment]
for the record
terraform {
  required_providers {
    ovirt = {
     #plugin must be in $HOME/.terraform.d/plugins/terraform.example.com/customname/ovirt/0.99.0/linux_amd64
       source  = "terraform.example.com/customname/ovirt"
       version = "0.99.0"
    }
  }
}

**Comment by janosdebugs** [comment]
Hey everyone, as [announced on the oVirt blog](https://blogs.ovirt.org/2021/10/important-changes-to-the-ovirt-terraform-provider/), we will address this with the 2.0 release. mid December hopefully.

**Comment by janosdebugs** [comment]
FYI an alpha build is now available and we are working on getting it released on the registry, but we hit a snag that the page isn't loading: https://registry.terraform.io/providers/oVirt/ovirt

If anyone knows how to fix this, please let us know.

**Comment by janosdebugs** [comment]
The new Terraform provider is now available here: https://registry.terraform.io/providers/oVirt/ovirt/
