### ISSUE TITLE
Documentation or info needed. VM booted from ISO

### ISSUE THREAD

**Issue by larssb** [oVirt/terraform-provider-ovirt#235]
As I am setting up a K3S cluster that is to be running on K3OS nodes. Where K3OS specifically is installed via the reformatted ISO approach (more [here](https://github.com/rancher/k3os#remastering-iso). I need a way to boot VM's via a CDROM, on an ISO image.

I've been through the [VM example](https://github.com/oVirt/terraform-provider-ovirt/tree/master/examples/vm) and the [docs](https://github.com/oVirt/terraform-provider-ovirt/tree/master/docs) and I can't seem to find a way to boot a VM on a CDROM/ISO.

What am I overlooking? Or is it not possible with the current state of *terraform-provider-ovirt*?

I've also tried the usual search engine magic. To see if I could find any examples out there. But, I was not able to.

Thank you.

**Comment by larssb** [comment]
Anybody?

**Comment by jake2184** [comment]
I don't think this is currently supported - the code enforces that a 'block device' must be assigned to a VM, and searches the 'disks' service on oVirt which only regards images or LUNs, not ISOs I don't think.

**Comment by larssb** [comment]
@jake184

Thank you very much for responding. So booting from a CDROM, which in a virtual environment, is a very normal go to solution, simply is not supported as I understand you. Fair enough. Too bad though.

I need to use an ISO in order to customize a K3OS installation. K3OS is a minimal OS to be used as the foundation for K3S - which in turn is a lightweight Kubernetes implementation.

Aarrrh dang. I wanted to use Terraform ... I’ll have to go the “automate the oVirt API way instead then”.

Does anyone know if it’s on the horizon to support ISO’s?

--
Mvh. / Kind regards
Lars Bengtsson

- Health is wealth, movement is medicine -

**Comment by jake2184** [comment]
It wouldn't be very hard to add - however I'm currently waiting for I think 6 PRs against this provider to be merged, so I wouldn't hold your breath for any feature update.

If you're happy to fork it & build yourself, it wouldn't be a huge amount of work to support it I don't think. 

You could also perhaps try a work around? Somehow copy/convert the ISO to a standard VHD image, and then you can mount that using the provider.

**Comment by janosdebugs** [comment]
Hey folks, this issue hasn't been touched for a while, so I'll close it. Feel free to reopen it if someone has time to add CD support to go-ovirt-client and the new Terraform provider.
