### ISSUE TITLE
ovoid loops when updating nested entity list 

### ISSUE THREAD

**Issue by emesika** [oVirt/terraform-provider-ovirt#239]
Some entities have nested entities like Affinity Group that has VMs and Hosts lists 
Those inner lists are subject to change and existing code sometimes requests changes on nested lists items instead of rebuilding the entire entities that contains those lists and update it in one call loosing the advantage of the transaction handling on RHV and potentially leaving the system in unstable state where some operations on the nested lists may succeed while others fails

**Comment by janosdebugs** [comment]
Hey @emesika I think we have this covered in 2.0 :)
