### ISSUE TITLE
root_password visible in terraform plan

### ISSUE THREAD

**Issue by JasonN3** [oVirt/terraform-provider-ovirt#244]
When running `terraform plan`, the root password is visible for new hosts. The field should be marked as sensitive using `Sensitive: true,` so the output will show "(sensitive value)" instead of the actual value. Any other resource types with a password should have the same thing done to them as well.

without "Sensitive: true":

   resource "ovirt_host" "host" {
       address       = "host_addr"
       cluster_id    = "cluster_id"
       id            = (known after apply)
       name          = "host_name"
       root_password = "YourSecurePassword"
}

with "Sensitive: true":

 resource "ovirt_host" "host" {
       address       = "host_addr"
       cluster_id    = "cluster_id"
       id            = (known after apply)
       name          = "host_name"
       root_password = (sensitive value)
}

**Comment by janoszen** [comment]
@JasonN3 thank you for your report. We have merged the patch and it will be in the next release (coming shortly).
