### ISSUE TITLE
Confused by install and initial setup

### ISSUE THREAD

**Issue by AnthonyHack** [oVirt/terraform-provider-ovirt#247]
Hi,

I'm having a bit of an issue getting this initialized for the first time. Here is my main.tf 

    terraform{
        required_providers{
            ovirt = {
                version = "~> 0.2.0"
                source = "ovirt"
            }
        }
    }

    provider "ovirt"{
      username = "XXXX"
      url      = "https://XXXXXXX/ovirt-engine/api"
      password = "XXXX"
    }

Terraform Version 

`terraform --version
Terraform v0.14.6`

The actual provider is here.

`pwd
/home/xxxx/.terraform.d/plugins
ls
terraform-provider-ovirt`

The error im seeing is the following

    terraform init

    Initializing the backend...

    Initializing provider plugins...
    - Finding hashicorp/ovirt versions matching "~> 0.2.0"...

    Error: Failed to query available provider packages

    Could not retrieve the list of available versions for provider
    hashicorp/ovirt: provider registry registry.terraform.io does not have a
    provider named registry.terraform.io/hashicorp/ovirt

    If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
    then please upgrade to Terraform v0.13 first and follow the upgrade guide for
    that release, which might help you address this problem.

If I change the source to point to the actual directory I get the following error.

    terraform init

    Initializing the backend...

    Initializing provider plugins...
    - Finding localhost/local/ovirt versions matching "~> 0.2.0"...

    Error: Failed to query available provider packages

    Could not retrieve the list of available versions for provider
    localhost/local/ovirt: could not connect to localhost: Failed to request
    discovery document: Get "https://localhost/.well-known/terraform.json": dial
    tcp 127.0.0.1:443: connect: connection refused

Its saying localhost/local because I created subdirectories inside of .terraform.d/plugins after reading some possible reasons for the initial failure. So not sure what that provider block in main.tf is supposed to look like if the provider is not on the terraform registry? Any ideas?

**Comment by jnach** [comment]
You may want to roll back to Terraform 0.11.x (I personally use a container image for this), and try again.

**Comment by bratucornel** [comment]
Hi,

Move the `terraform-provider-ovirt` binary in `~/.terraform.d/plugins/{NAMESPACE}/{VENDOR}/ovirt/0.2.0/{TARGET}/`

The TARGET specifies a particular target platform using a format like `darwin_amd64`, `linux_arm`, `windows_amd64`, etc.

Then, you can use the provider like this:

```tf
terraform {
  required_providers {
    ovirt = {
      version = "0.2.0"
      source  = "{NAMESPACE}/{VENDOR}/ovirt"
    }
  }
}
```

**Comment by AnthonyHack** [comment]
Thanks @bratucornel that solved my issue.
