### ISSUE TITLE
ovirt_disk_attachment and HTTP 404

### ISSUE THREAD

**Issue by xiriox** [oVirt/terraform-provider-ovirt#249]
Hello,

I continue testing this provider, and now I am adding an additional disk to the virtual machine, but at the end of the creation process I get:

_Error: Error applying plan:

1 error occurred:
        * module.Virtual-Machine.ovirt_disk_attachment.diskattachment: 1 error occurred:
        * ovirt_disk_attachment.diskattachment: HTTP response code is "404". HTTP response message is "404 Not Found"._

My resource code is:

`resource "ovirt_disk" "disk" {
  name              = "${var.vm_name}-disk-2"
  alias             = "vmname_Disk2" # "${var.vm_name}-disk-attach"
  size              = "${var.disk-size}"
  format            = "${var.disk-format}"
  storage_domain_id = "${var.disk-storage_domain_id}"
  sparse            = "${var.sparse}"
  shareable         = "${var.shareable}"
  #depends_on      = ["ovirt_vm.vm"]
}

resource "ovirt_disk_attachment" "diskattachment" {
  vm_id                = "${var.vm_id}"
  disk_id              = "${ovirt_disk.disk.id}"
  active               = "${var.active}"
  bootable             = "${var.bootable}"
  interface            = "${var.interface}"
  read_only            = "${var.read_only}"
  use_scsi_reservation = "${var.use_scsi_reservation}"
  depends_on      = ["ovirt_disk.disk"]
}
`
The disk is not added to the virtual machine when the process ends but it is created.

I use Terraform v0.11.14

¿any ideas?

thank you,

Best regards

**Comment by janosdebugs** [comment]
This issue seems to be for the "v0" version of the Terraform provider and should be resolved in the new "v2" version. Closing this issue, please reopen if it persists after an update.
