### ISSUE TITLE
terraform 0.12.0+

### ISSUE THREAD

**Issue by BoLB23** [oVirt/terraform-provider-ovirt#263]
Currently this requires terraform 0.11.X. Is there any plan to update this for newer terraform versions?

**Comment by jake2184** [comment]
It definitely supports at least v0.12.29.

**Comment by BoLB23** [comment]
I am going off the requirements page:

![image](https://user-images.githubusercontent.com/48114057/116624497-013bc100-a916-11eb-98f4-e722b21db5a4.png)

**Comment by cregkly** [comment]
Here is an example on how to get the provider to initialise on version 0.13+

https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers

```
terraform {
    required_version = ">= 0.13"
    required_providers { 
        ovirt = { 
            source  = "local/ovirt/ovirt"
            version = "0.99.0"
        }
    }
}
```
The corresponding folder structure for linux would then be:
```
~/.terraform.d/plugins/local/ovirt/ovirt/0.99.0/linux_amd64/terraform-provider-ovirt_v0.99.0
```

This just enables initialisation, I have not actually tried to use the provider with these versions and can't comment if it works.

**Comment by janosdebugs** [comment]
Hey everyone, we are rebuilding the provider as [announced here](https://blogs.ovirt.org/2021/10/important-changes-to-the-ovirt-terraform-provider/). This issue will be addressed as part of that overhaul.

**Comment by janosdebugs** [comment]
The first alpha build for v2 is available now and will be published on the Terraform registry as soon as we have sorted out our syncing issues.
