### ISSUE TITLE
Getting 400 on affinity group

### ISSUE THREAD

**Issue by jake2184** [oVirt/terraform-provider-ovirt#266]
I've been testing the functionality of adding affinity groups to VMs at creation time.

I am occasionally hitting a 400 error when creating a VM when it tries to add it to an affinity group. This causes the VM to be tainted.

My steps:
- Create 10 VMs with TF. 
- Delete them all in the GUI
- Rerun TF, which redeploys the VMs. I hit the 400 error here. 
 
The error is non-deteministic - I ran the above step twice (so 3 rounds of VM deployments). First run no errors, second run 2 errors, third run 1 error. 

Looking at engine logs, I think it is hitting a race condition - I see SQL errors about affinity_group_pk violations. Is there some background process that needs to clear the values from the affinity group table which takes some time after the VM was deleted? This seems odd.

**Comment by jake2184** [comment]
FYI I've raised a RedHat support case about this providing engine logs to them.

**Comment by Gal-Zaidman** [comment]
Hi Jake,

Yep you are right it is a bug in the engine, and I will look it up for you and it should be handled in the next version of the engine.
The way to avoid it is to not create the VMs is parallel, we have this PR https://github.com/oVirt/terraform-provider-ovirt/pull/262 to limit parallelism in the provider

**Comment by jake2184** [comment]
Bug has been fixed upstream, and workaround in place.
