### ISSUE TITLE
Publish module in Terraform Registry

### ISSUE THREAD

**Issue by CalvinVoxox** [oVirt/terraform-provider-ovirt#279]
Is there a specific reason this provider is not registered in the HashiCorp Terraform Registry?

It should be straightforward to add the provider, but only the owners of the repository can do it.

**Comment by zdzielinski** [comment]
This would be a nice feature for a first or subsequent "finalized" release.

**Comment by emesika** [comment]
@CalvinVoxox 

it is in out TODO list , thanks for your comment

**Comment by janosdebugs** [comment]
Hey everyone, we'll be tracking this under #230 and it will be addressed in the new v2.0.0 release.
