### ISSUE TITLE
Windows Server issues

### ISSUE THREAD

**Issue by msmagnanijr** [oVirt/terraform-provider-ovirt#290]
Hey, 

I'm using this plugin to create some VMs with Windows Server 2019 and the configuration made is not being honored.
When this happens on Linux it's usually because I don't have the cloud-init installed in the template... in that case is there something equivalent for Windows?

I already installed in the template the virtio-win driver from "virtio-win-1.9.19.iso". 

In my case, the VM went up correctly but the static IP was not honored.

Thanks!

**Comment by msmagnanijr** [comment]
![Screenshot from 2021-09-25 21-46-06](https://user-images.githubusercontent.com/10897399/134789511-e51eae67-b5a6-47b4-979e-068ac8bcb750.png)
![Screenshot from 2021-09-25 21-46-28](https://user-images.githubusercontent.com/10897399/134789514-b2370b71-2042-49af-9338-1f0a045f047e.png)

**Comment by janosdebugs** [comment]
Hello,

For Windows you can use cloudbase-init to set up the server, it should work. This is not a Terraform provider issue.

As for the static IP, please check if creating the VM from the UI with the same settings works. If it works from the UI, we'll look into it, otherwise it's not a TF provider issue.

Thanks!

**Comment by msmagnanijr** [comment]
> Hello,
> 
> For Windows you can use [cloudbase-init](https://cloudbase.it/cloudbase-init/) to set up the server, it should work. This is not a Terraform provider issue.
> 
> As for the static IP, please check if creating the VM from the UI with the same settings works. If it works from the UI, we'll look into it, otherwise it's not a TF provider issue.
> 
> Thanks!

@janosdebugs If I do it manually by the UI it works. I will also test this on the golang client that your team is developing.... I just don't remember the project link.

**Comment by janosdebugs** [comment]
> > Hello,
> > 
> > For Windows you can use [cloudbase-init](https://cloudbase.it/cloudbase-init/) to set up the server, it should work. This is not a Terraform provider issue.
> > 
> > As for the static IP, please check if creating the VM from the UI with the same settings works. If it works from the UI, we'll look into it, otherwise it's not a TF provider issue.
> > 
> > Thanks!
> 
> @janosdebugs If I do it manually by the UI it works. I will also test this on the golang client that your team is developing.... I just don't remember the project link.   thanks!
> 
> 

Thank you very much for your help, it seems to be a bug in the TF provider indeed. The new client lib is at https://github.com/ovirt/go-ovirt-client . It doesn't support adding NIC IP's yet, but PRs are most welcome.

**Comment by msmagnanijr** [comment]
@janosdebugs the go-ovirt-client is amazing! I'm really looking forward to seeing the next steps... I think it will be a great replacement for this tf provider.  I will test it and if I have something interesting I will definitely contribute.

**Comment by janosdebugs** [comment]
@msmagnanijr thank you very much, I'll try and keep this thread updated. The new TF provider is provisionally located here: github.com/haveyoudebuggedit/terraform-provider-ovirt (We'll move it if we made a decision to go with this solution.)

**Comment by janosdebugs** [comment]
I took a look at the source code of the NIC implementation and it seems that the current TF provider pretty much passes the NIC configuration directly to the "initialization" part of the VM, which in turn should be read by the agent on Windows to configure the NICs. I'm not an expert on oVirt internals, but I'm pretty sure that the KVM guest agent doesn't do that. In other words, you'll probably have to make cloudbase-init work. It may be worth posting the question on ovirt-users as it seems to be unrelated to the Terraform provider.

**Comment by msmagnanijr** [comment]
> I took a look at the source code of the NIC implementation and it seems that the current TF provider pretty much passes the NIC configuration directly to the "initialization" part of the VM, which in turn should be read by the agent on Windows to configure the NICs. I'm not an expert on oVirt internals, but I'm pretty sure that the KVM guest agent doesn't do that. In other words, you'll probably have to make cloudbase-init work. It may be worth posting the question on ovirt-users as it seems to be unrelated to the Terraform provider.

Thank you for the tips! I'll try to solve this then on the "oVirt" side since it's not a tf provider issue.

By the way, do you recommend any Ansible plugin to use in with this plugin? I was using this https://github.com/radekg/terraform-provisioner-ansible but it was archived.

Thanks!

**Comment by janosdebugs** [comment]
Typically, you'd put the Ansible config in the "userdata" section. Cloud-Init, or Cloudbase-Init give you the ability to provision files and then run a small scripts. You don't need a separate provider for that. However, keep in mind that most platforms have size limit for the user data, I don't know if that's true for oVirt too. You'll have to read the docs of whatever init program you want to use for how to do that exactly.

Since this thread is no longer a problem with the TF provider I'll close this issue. Tet's take this discussion over to ovirt-users or the [discussions page](https://github.com/oVirt/terraform-provider-ovirt/discussions) please.
