### ISSUE TITLE
Building source code fails with error "duplicate method on client_disk.go"

### ISSUE THREAD

**Issue by figueiredorj** [oVirt/terraform-provider-ovirt#297]
## Describe the bug

Please enter a clear and concise description of what the bug is.

## To Reproduce
using WSL ubuntu image
installl golang (sudo apt-get install)
installed version 1.13.?
uninstall golang
wget latest golang version
unzip 
mv to usr
export path/set profile
version 1.17.3

If you can please provide the steps to reproduce the issue.

1. ... Make install

## Expected behavior
Was expecting to create provider to add on terraform project

## failed
![image](https://user-images.githubusercontent.com/4283523/142245477-f87d5b4c-ee64-40ec-aa7a-13d3dd311d7f.png)

tells me that Read method is duplicated; trying to understand if that has to be with version of go (???) or if there is some mistake (go is unknown currently)

**Comment by janosdebugs** [comment]
Hey @figueiredorj we are currently in the process of reworking the Terraform provider as announced [here](https://blogs.ovirt.org/2021/10/important-changes-to-the-ovirt-terraform-provider/). Until we are finished with rebuilding it please use the version from the `v0` branch.

**Comment by figueiredorj** [comment]
thanks Janos,
done so.

can you also let me know from provider that is under work, which features
are already available? or at least, point me in the right direction :)

Figueiredo, Ricardo José Andrade
Email: ***@***.***

**Comment by janosdebugs** [comment]
Hey @figueiredorj the new provider is not usable yet. I'll keep this issue open and inform you when it is usable.

**Comment by figueiredorj** [comment]
Cool, thanks!

A sábado, 20 de nov de 2021, 20:49, Janos Bonic ***@***.***>
escreveu:
