### ISSUE TITLE
404 on link to documentation

### ISSUE THREAD

**Issue by nickbouwhuis** [oVirt/terraform-provider-ovirt#314]
The README.md file states
> The detailed documentation can be found in the [Terraform registry](https://registry.terraform.io/providers/ovirt/ovirt/latest/docs).

However, the linked page (https://registry.terraform.io/providers/ovirt/ovirt/latest/docs) results in a 404 as of 2022-01-31:
![Screenshot from 2022-02-01 14-42-50](https://user-images.githubusercontent.com/2922075/151979210-5c4b907f-a916-40b4-9455-cfc8fabf0c4a.png)

Where can I find up-to-date documentation for this provider? Can the link be updated?

**Comment by janosdebugs** [comment]
Hey @nickbouwhuis we are still reworking the Terraform provider. Unfortunately, our timeline got pushed back a few months due to a team member leaving. I'll leave this issue open to make sure this is resolved when we push the new version.

**Comment by janosdebugs** [comment]
This issue has now been resolved and the Terraform provider is available here: https://registry.terraform.io/providers/oVirt/ovirt/
