### ISSUE TITLE
provider is no longer listed in https://registry.terraform.io/

### ISSUE THREAD

**Issue by rpkish** [oVirt/terraform-provider-ovirt#401]
## Describe the bug

Documentation points to https://registry.terraform.io/, however this provider no longer seems to exist.

Please enter a clear and concise description of what the bug is.

## To Reproduce

If you can please provide the steps to reproduce the issue.

1. use ovirt/ovirt provider
```
terraform {
  required_providers {
    ovirt = {
      source = "ovirt/ovirt"
    }
  }
}
```
2. run terraform init
```
Initializing provider plugins...
- Finding latest version of ovirt/ovirt...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider ovirt/ovirt: provider registry.terraform.io/ovirt/ovirt was not found in any of the search locations
│ 
│   - registry registry.terraform.io
```
3. Note the readme.md now points to a non existent link: https://registry.terraform.io/providers/ovirt/ovirt/latest/docs

## Expected behavior

Provider is downloaded correctly when running `terraform init`

Please describe what you would expect to happen.

**Comment by janosdebugs** [comment]
Hello @rpkish we are attempting to release the provider to the TF registry for the first time, but it seems we have hit a bug on their side and are unable to do so. We'll let youbknow once the issue is resolved.

**Comment by janosdebugs** [comment]
This issue has been resolved and the Terraform provider is now available here: https://registry.terraform.io/providers/oVirt/ovirt/
