### ISSUE TITLE
VM creation fails due to no serial console

### ISSUE THREAD

**Issue by janosdebugs** [oVirt/terraform-provider-ovirt#411]
## Describe the bug

VM creation fails due to `field_missing: no serial console field found on vm object)`

Reason: ovirt/go-ovirt-client#211

**Comment by eslutsky** [comment]
it appears that  Console oVirt API only returned if the VM  status is up , otherwise its nil

**Comment by janosdebugs** [comment]
@engelmi this should now be fixed, right?
