### ISSUE TITLE
Terraform x OVN

### ISSUE THREAD

**Issue by junnbj** [oVirt/terraform-provider-ovirt#481]
hello everyone 
Someone knows if exist way to connect terraform with OVN?
...

**Comment by engelmi** [comment]
Hi @junnbj, 
although an [ovirt-ovn-integration](https://github.com/oVirt/ovirt-provider-ovn) exists, there are no dedicated API endpoints to configure it as far as I know. Therefore, this terraform provider tailored towards oVirt does not support this. According to the [doc](https://github.com/oVirt/ovirt-provider-ovn#configuration), however, you can try to use the initialization script for VMs to pass the OVN configuration - but that is just a vague guess.
