### ISSUE TITLE
Help VM disk size from template

### ISSUE THREAD

**Issue by cello86** [oVirt/terraform-provider-ovirt#507]
Hi,
I tried to create a VM from an OVF template imported on ovirt 4 but the VM has a disk size of 2 GBs and if I tried to attach a different disk this operation gone in timeout.

Can you help me to understand the correct procedure to set the correct space on the new vm?

Thanks, 
Marcello

**Comment by engelmi** [comment]
Hi @cello86, could you provide more details, e.g. with a log dump of this, please?

**Comment by cello86** [comment]
Hi @engelmi,
the issue was related to wrong OVF import into ovirt and this created an image with a small disk. This problema has been resolved with manual import from UI of the OVF image.

Thanks,
Marcello
