### ISSUE TITLE
Getting "[Network interface is already in use.]" when creating ovirt_vnic resource

### ISSUE THREAD

**Issue by yalinglee** [oVirt/terraform-provider-ovirt#61]
I have a template with a network interface "nic1" that doesn't have any vnic profile assigned to it. Using the Ovirt UI, I'm able to pick a vnic profile when I start a new VM using that template. However, when I try to do this via terraform, I would get the `[Network interface is already in use.]` error.

Here is my terraform code:
```
resource "ovirt_vm" "my_vm" {
  name      = "my_vm"
  cluster_id   = "${var.cluster_id}"
  template_id  = "${var.template_id}"
  cores     = 2
}

resource "ovirt_vnic" "nic1" {
  vm_id = "${ovirt_vm.my_vm.id}"
  name = "nic1"
  vnic_profile_id = "${var.vnic_profile_id}"
}
```

Here is the output: 
```
ovirt_vm.my_vm: Creating...
  cluster_id: "" => "3b1f3529-13bb-1420-0045-0000000002b1"
  cores:      "" => "2"
  name:       "" => "my_vm"
  sockets:    "" => "1"
  status:     "" => "<computed>"
  template_id:   "" => "671119ed-1ab4-41d7-b371-c2fc910a2e0d"
  threads:    "" => "1"
ovirt_vm.my_vm: Still creating... (10s elapsed)
ovirt_vm.my_vm: Still creating... (20s elapsed)
ovirt_vm.my_vm: Still creating... (30s elapsed)
ovirt_vm.my_vm: Creation complete after 31s (ID: eef41089-ed50-4805-b58d-dcc017be769f)
ovirt_vnic.nic1: Creating...
  name:            "" => "nic1"
  vm_id:           "" => "eef41089-ed50-4805-b58d-dcc017be769f"
  vnic_profile_id: "" => "7d735393-d8d8-4d96-98ca-2f8d272aa5a4"

Error: Error applying plan:

1 error(s) occurred:

* ovirt_vnic.nic1: 1 error(s) occurred:

* ovirt_vnic.nic1: Fault reason is "Operation Failed". Fault detail is "[Network interface is already in use.]". HTTP response code is "409". HTTP response message is "409 Conflict".
```

Am I using the `ovirt_vnic` resource correctly? Is there a way to use a template and assign the vnic profile during the VM creation with the terraform provider?

**Comment by imjoey** [comment]
hi @yalinglee , unfortunately template customization at VM creation is not supported right now. The missing feature may be something as below:

```HCL
resource "ovirt_vm" "my_vm" {
  name      = "my_vm"
  template {
     id  = "${var.template_id}"
     # NICs customizations
     nic {
       name = "nic1-new"    # rename NIC name
       vnic_profile_id = "${var.vnic_profile_id}"
     }
     nic {
       name = "nic2-new"    # rename NIC name
       vnic_profile_id = "${var.vnic_profile_2_id}"
     }
     # Disks customizations
     disk {
       name = "disk1-new"   # rename disk name
     }
  }
  cluster_id   = "${var.cluster_id}"
  cores     = 2
}
```

Besides the vNICs customizations, we may also need to change the names of disks defined in template when creating a template-based VM. It is not supported neither.

Noted that the resource `ovirt_vnic ` indicates a vNIC which is independent of the template and it is explicitly defined and maintained by terraform. While the ones generated by a template are not able to be detected or managed by terraform. So if you still want to use the `nic1` defined in template, please remove the `ovirt_vnic` definition and refer to the oVirt-UI to assign a vnic profle to `nic1`. 

Sorry for the inconvenience. I will fix this ASAP.

**Comment by yalinglee** [comment]
@imjoey Thanks for the explanation. I can go around this issue for now by removing the nic from the template and just defining nic1 using Terraform. But yes, it would be helpful to be able to customize the template during VM creation. Also, are there plans to start versioning the provider?

**Comment by imjoey** [comment]
@yalinglee  Now I'm considering to make it feature-freeze for releasing the first version.  While there still has need to add more acceptance test cases and do overall test to ensure the stability. The first stable version will released in the next couple of days. If you have any suggestions on that, please let me know. Thanks for your feedback. 😄

**Comment by yalinglee** [comment]
A stable release would be great. Looking forward to it!

**Comment by emesika** [comment]
Sorry for the delay, we are doing a cleanup on all issues in order to be more responsive, is this issue still relevant or we can delete it ?

**Comment by yalinglee** [comment]
@emesika feel free to delete it since we've found a workaround. Thanks!
