### ISSUE TITLE
Examples 

### ISSUE THREAD

**Issue by inge4pres** [oVirt/terraform-provider-ovirt#73]
Hi @imjoey 

thank you for open sourcing this work 😄 
As opened in the original project https://github.com/EMSL-MSC/terraform-provider-ovirt/issues/10 it would be optimal to have examples on how to consume this plugin.

Thank you

**Comment by imjoey** [comment]
hi @inge4pres , thanks for your feedback. The missing parts, including website and examples, will be added soon. Now you could refer to the `examples/` and acc-test files for some basic usages. Thanks again. 😄

**Comment by imjoey** [comment]
hi @inge4pres , I just have added the missing documents hosted by `website`. You could refer the latest `README.md` and #81 for details. Any feedbacks are extremely welcome and appreciated. Thanks.

**Comment by rgolangh** [comment]
@imjoey can we close this?

**Comment by imjoey** [comment]
@rgolangh Yes, I think we could. For the docs has been added for use guidance.
