### ISSUE TITLE
Request for New Resource: ovirt_template

### ISSUE THREAD

**Issue by imjoey** [oVirt/terraform-provider-ovirt#83]

**Comment by emesika** [comment]
Sorry for the delay, we are doing a cleanup on all issues in order to be more responsive, is this issue still relevant or we can delete it ?

**Comment by emesika** [comment]
closing this issue after not getting an answer if it still relevant, please feel free to open again if needed

**Comment by emesika** [comment]
closing this issue after not getting an answer if it still relevant, please feel free to open again if needed
