### ISSUE TITLE
resource/ovirt_vm: Template customization is not supported

### ISSUE THREAD

**Issue by imjoey** [oVirt/terraform-provider-ovirt#84]

**Comment by emesika** [comment]
Sorry for the delay, we are doing a cleanup on all issues in order to be more responsive, is this issue still relevant or we can delete it ?

**Comment by trexmaster** [comment]
Hi @emesika I'm not sure if this is the right place to post this or if I should create a new issue, the only form of template customization I would need is to be able to resize the VM's base disk's size. 

I've tried the following "process" :
- create the vm through the resource ovirt_vm from a template (in this case an Ubuntu 20.04 cloud image)
- Get the disk ID, format and storage_domain_size using a datasource ovirt_disk
- change the disk's name, alias, and size through a resource ovirt_disk

But the resource ovirt_disk only supports identifying a disk by its name and doesn't support doing so by its id (actually it doesn't support specifying the id at all) so no dice.

**Comment by emesika** [comment]
@trexmaster 

Please see docs/resources/disk.md , I am copying the relevant sentence :

## Attributes Reference

In addition to all arguments above, the following attributes are exported:

* `id` - The ID of oVirt Disk


Please let me know if this issue can be closed

**Comment by trexmaster** [comment]
Hi @emesika , I later found out from **examples/vm/main.tf** that if you leave out the disk's ID in the **block_device** block it would just resize the template's existing disk (I'm assuming the first one if there are multiple ones, but I haven't actually tested this). Here's the example in question : 
```
block_device {
    disk_id   = "${ovirt_disk.my_disk_1.id}"  // optional
    interface = "virtio"
    size      = 120   // size in GiB - in case disk_id is not passed, this would extend the disk.
    alias          = "my_vm_1" // optional. human friendly disk name on the disks list.
    storage_domain = "lun-5TB" // optional. define storage domain where will be created disks for VM.
                               // Applied only for deploy VM from Template. disk_id shoud be removed.
  }
```

I would probably add it to the VM resource documentation though as I think not too many people will go check the examples in the Github repo once the provider's published on Terraform's registry.

**Comment by janosdebugs** [comment]
This issue seems to be for the "v0" version of the Terraform provider and should be resolved in the new "v2" version. Closing this issue, please reopen if it persists after an update.
